substitutions:
  name: waterheater
  io_username: !secret adafruit_io_username

esphome:
  name: ${name}

esp8266:
  board: d1_mini

# Enable logging
logger:
  level: VERBOSE

api:
  password: !secret local_api_password
  # Disable automatic reboot every 15 minutes if there is no native API connection;
  # comment out next line if using with Home Assistant and the native ESPHome API.
  reboot_timeout: 0s

ota:
  platform: esphome
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: '${name} Fallback Hotspot'
    password: !secret hotspot_password

captive_portal:

mqtt:
  broker: 'io.adafruit.com'
  username: ${io_username}
  password: !secret adafruit_io_key
  discovery: false
  topic_prefix: '${io_username}/feeds'
  birth_message:
    topic: '${io_username}/feeds/${name}-status'
    payload: Online
  will_message:
    topic: '${io_username}/feeds/${name}-status'
    payload: Offline-will
  shutdown_message:
    topic: '${io_username}/feeds/${name}-status'
    payload: Offline-clean
  log_topic:

one_wire:
  platform: gpio
  pin: D5

sensor:
  - platform: dallas_temp
    name: Hot water
    state_topic: ${io_username}/feeds/hot_water
    filters:
      - throttle_average: 30s
